version: 2

run_tests: &run_tests
  steps:
    - checkout
    - run: sudo apt update
    - run: sudo apt install -y default-mysql-client
    - run: bundle install
    - run: bundle exec rake test
    - run: bundle exec rake performance_test

jobs:

  # Ruby 2.4
  test-2.4-with-4.2:
    docker:
      - image: circleci/ruby:2.4
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails4.2.gemfile
    <<: *run_tests
  test-2.4-with-5.1:
    docker:
      - image: circleci/ruby:2.4
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.1.gemfile
    <<: *run_tests
  test-2.4-with-5.2:
    docker:
      - image: circleci/ruby:2.4
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.2.gemfile
    <<: *run_tests

  # Ruby 2.5
  test-2.5-with-4.2:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails4.2.gemfile
    <<: *run_tests
  test-2.5-with-5.1:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.1.gemfile
    <<: *run_tests
  test-2.5-with-5.2:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.2.gemfile
    <<: *run_tests
  test-2.5-with-6.0:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.0.gemfile
    <<: *run_tests
  test-2.5-with-6.1:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.1.gemfile
    <<: *run_tests

  # Ruby 2.6
  test-2.6-with-4.2:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails4.2.gemfile
    <<: *run_tests
  test-2.6-with-5.1:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.1.gemfile
    <<: *run_tests
  test-2.6-with-5.2:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.2.gemfile
    <<: *run_tests
  test-2.6-with-6.0:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.0.gemfile
    <<: *run_tests
  test-2.6-with-6.1:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.1.gemfile
    <<: *run_tests

  # Ruby 2.7
  test-2.7-with-5.1:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.1.gemfile
    <<: *run_tests
  test-2.7-with-5.2:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails5.2.gemfile
    <<: *run_tests
  test-2.7-with-6.0:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.0.gemfile
    <<: *run_tests
  test-2.7-with-6.1:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.1.gemfile
    <<: *run_tests
  test-2.7-with-7.0:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails7.0.gemfile
    <<: *run_tests

  # Ruby 3.0
  test-3.0-with-6.0:
    docker:
      - image: circleci/ruby:3.0
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.0.gemfile
    <<: *run_tests
  test-3.0-with-6.1:
    docker:
      - image: circleci/ruby:3.0
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.1.gemfile
    <<: *run_tests
  test-3.0-with-7.0:
    docker:
      - image: circleci/ruby:3.0
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails7.0.gemfile
    <<: *run_tests

  # Ruby 3.1
  test-3.1-with-6.1:
    docker:
      - image: cimg/ruby:3.1.2
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails6.1.gemfile
    <<: *run_tests
  test-3.1-with-7.0:
    docker:
      - image: cimg/ruby:3.1.2
      - image: circleci/mysql:5.7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails7.0.gemfile
    <<: *run_tests

workflows:
  version: 2
  build:
    jobs:

      - test-2.4-with-4.2
      - test-2.4-with-5.1
      - test-2.4-with-5.2

      - test-2.5-with-4.2
      - test-2.5-with-5.1
      - test-2.5-with-5.2
      - test-2.5-with-6.0
      - test-2.5-with-6.1

      - test-2.6-with-4.2
      - test-2.6-with-5.1
      - test-2.6-with-5.2
      - test-2.6-with-6.0
      - test-2.6-with-6.1

      - test-2.7-with-5.1
      - test-2.7-with-5.2
      - test-2.7-with-6.0
      - test-2.7-with-6.1
      - test-2.7-with-7.0

      - test-3.0-with-6.0
      - test-3.0-with-6.1
      - test-3.0-with-7.0

      - test-3.1-with-6.1
      - test-3.1-with-7.0
